apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php-apache
          image: php:8.2-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: php-code
              mountPath: /var/www/html
      volumes:
        - name: php-code
          configMap:
            name: php-code
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-code
data:
  index.php: |
    <?php
    $servername = "mysql";
    $username = "user";
    $password = "userpass";
    $database = "myapp";

    $conn = new mysqli($servername, $username, $password, $database);
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }

    $sql = "SELECT id, name, price FROM products";
    $result = $conn->query($sql);
    ?>

    <!DOCTYPE html>
    <html>
    <head><title>Product List</title></head>
    <body>
    <h1>Products</h1>
    <table border="1">
      <tr><th>ID</th><th>Name</th><th>Price</th></tr>
      <?php while($row = $result->fetch_assoc()): ?>
        <tr>
          <td><?= $row['id'] ?></td>
          <td><?= $row['name'] ?></td>
          <td><?= $row['price'] ?></td>
        </tr>
      <?php endwhile; ?>
    </table>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: php
