apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS products (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        price DECIMAL(10,2) NOT NULL
    );

    INSERT INTO products (name, price) VALUES
    ('Laptop', 1500.00),
    ('Keyboard', 50.00),
    ('Mouse', 25.00);
