apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php-apache
          image: php:8.2-apache
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: mysql-secrets
          volumeMounts:
            - name: php-code
              mountPath: /var/www/html
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      volumes:
        - name: php-code
          configMap:
            name: php-code
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: php
